### ISSUE TITLE
Link to spec

### ISSUE THREAD

**Issue by oberstet** [mulderr/haskell-wamp#1]
Awesome! WAMP for Haskell;)

The link to the WAMP spec is broken .. would be safer to link to http://wamp-proto.org/spec/ ..

Btw: are you planning to continue this project? Do you want it (already) to be listed at the WAMP Web site?

**Comment by mulderr** [comment]
Hi! Thanks, link fixed.

I am currently occupied with other stuff and doubt I will find the time to push this to the point of usability in production. I believe the client code could be made fairly spec compliant with a bit more work. I have that on my todo list but unfortunatelly not a priority right now.

The router on the other hand is missing a couple key features. Some of the changes needed to fully comply with the spec would require a major redesign of my simplistic, ultra-concurrent approach. If I recall correctly I hit a bit of a wall with ordering guarantees. At this point I don't even have a clear idea how to tackle that. It would probably require some clever (per client?) form of queuing which would ineed complicate the code a lot.

I think it maybe better to err on the side of caution and not list this on the WAMP web site but I don't really have a strong opinion either way. If you do end up including it though, please make sure to mark it as experimental until further notice ;)

**Comment by oberstet** [comment]
@mulderr thanks for explaining! I've added the link to http://wamp-proto.org/implementations/, but added wording to mark it as experimental ..
