### ISSUE TITLE
`wamp-client`, `warp-client` confusion.

### ISSUE THREAD

**Issue by AndrewRademacher** [mulderr/haskell-wamp#5]
In the project folder `wamp-client`, the cabal package is actually listed as `warp-client`. The packages inside that project are `Network.Wamp.*`. Is it a typo that the cabal file is called `warp-client`?

**Comment by mulderr** [comment]
Hmm. It definitelly looks like a typo. I see no reason right now why it shoulnt be changed to wamp-client.

**Comment by mulderr** [comment]
Fixed in 654129f.

This would normally require a version bump at this stage I guess still anything goes.

**Comment by AndrewRademacher** [comment]
Thank you for the quick response.
