### ISSUE TITLE
Typo in wamp-client/package.yaml

### ISSUE THREAD

**Issue by matteougolotti** [mulderr/haskell-wamp#7]
Hi, I'm having some issues building with stack on Windows and Mac as it seems that stack generates a new .cabal file named warp-client.cabal in the wamp-client subfolder.

It looks like this can be fixed by changing the name on the first line of wamp-client/package.yaml from warp-client to wamp-client.

**Comment by mulderr** [comment]
Right, the name has been recently changed. I totally forgot about this, since I pretty much don't ever use stack. Thanks for pointing this out!
